aa_contacts/urls.py
from django.urls import path, re_path

from . import views
from .api import api

app_name = 'aa_contacts'


urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('api/', api.urls),
    re_path('^r/', views.react_view, name='react_view'),
    path('alliance/<int:alliance_pk>/', views.alliance_contacts, name='alliance_contacts'),
    path('alliance/add_token/', views.add_alliance_token, name='add_alliance_token'),
    path('alliance/update/<int:alliance_pk>/', views.update_alliance, name='update_alliance'),
    path('alliance/edit_contact/<int:contact_pk>/', views.update_alliance_contact, name='update_alliance_contact'),
    path('corporation/<int:corporation_pk>/', views.corporation_contacts, name='corporation_contacts'),
    path('corporation/add_token/', views.add_corporation_token, name='add_corporation_token'),
    path('corporation/update/<int:corporation_pk>/', views.update_corporation, name='update_corporation'),
    path('corporation/edit_contact/<int:contact_pk>/', views.update_corporation_contact, name='update_corporation_contact'),
]

aa_contacts/templates/aa_contacts/alliance_contacts.html
{% extends 'aa_contacts/base.html' %}
{% load i18n %}

{% block page_title %}{% translate "Alliance Contacts" %}{% endblock page_title %}

{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock %}

{% block aacontactscontent %}
    {% include "framework/header/page-header.html" with title=alliance.alliance_name|add:" Contacts" %}
    {% if perms.aa_contacts.manage_alliance_contacts %}
        <div class="row justify-content-center my-3">
            <div class="col-6">
                <div class="card-group">
                    <div class="card text-center">
                        <div class="card-header">
                            {% translate "Last update" %}
                        </div>
                        <div class="card-body">
                            <p>{{ token.last_update|date:"d/m/Y G:i e" }}</p>
                        </div>
                    </div>
                    <div class="card text-center">
                        <div class="card-header">
                            {% translate "Actions" %}
                        </div>
                        <div class="card-body">
                            <a class="btn btn-primary" href="{% url "aa_contacts:update_alliance" alliance.pk %}">{% translate "Update" %}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {% include "aa_contacts/contact_list.html" with view_notes=perms.aa_contacts.view_alliance_notes edit_notes=perms.aa_contacts.manage_alliance_contacts contacts=contacts edit_url="aa_contacts:update_alliance_contact" %}
            </div>
        </div>
    </div>
{% endblock aacontactscontent %}

{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
    {% include "bundles/filterdropdown-js.html" %}
{% endblock extra_javascript %}

aa_contacts/templates/aa_contacts/base.html
{% extends 'allianceauth/base-bs5.html' %}

{% load i18n %}

{% block page_title %}
    {% translate "Contacts" %}
{% endblock %}

{% block header_nav_brand %}
    {% translate "Contacts" %}
{% endblock header_nav_brand %}

{% block header_nav_collapse_left %}
    {% include "aa_contacts/switch_frontend_version.html" %}
{% endblock header_nav_collapse_left %}

{% block content %}
    <div class="row">
        {% block aacontactscontent %}{% endblock aacontactscontent %}
    </div>
{% endblock content %}

aa_contacts/templates/aa_contacts/contact_list.html
{% load i18n %}

<div class="table-responsive">
    <table id="contact-table" class="table table-aa">
        <thead>
            <tr>
                <th>{% translate "Contact" %}</th>
                <th>{% translate "Contact Type" %}</th>
                <th>{% translate "Labels" %}</th>
                <th>{% translate "Standing" %}</th>
                {% if view_notes %}<th>{% translate "Notes" %}</th>{% endif %}
                {% if view_notes and edit_notes %}<th></th>{% endif %}
            </tr>
        </thead>

        <tbody>
            {% for contact in contacts %}
                <tr>
                    <td>
                        <img src="{{ contact.image_src }}" class="rounded me-2">
                        {{ contact.contact_name }}
                    </td>
                    <td>{{ contact.contact_type }}</td>
                    <td>{% for label in contact.labels.all %}{{ label.label_name }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                    <td>{{ contact.standing }}</td>
                    {% if view_notes %}<td>{{ contact.notes }}</td>{% endif %}
                    {% if view_notes and edit_notes %}
                        <td><a href="{% url edit_url contact.pk %}" class="btn btn-outline-success btn-sm"><i class="fa-solid fa-pen"></i></a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<script>
    window.onload = function() {
        $('#contact-table').DataTable({
            {% if view_notes and edit_notes %}
            columnDefs: [
                { targets: [5], sortable: false, searchable: false }
            ],
            {% endif %}
            "pageLength": 50,
            filterDropDown: {
                bootstrap: true,
                bootstrap_version: 5,
                columns: [
                    {
                        idx: 1,
                        title: 'Contact Type'
                    },
                    {
                        idx: 2,
                        title: 'Labels'
                    },
                    {
                        idx: 3,
                        title: 'Standing'
                    }
                ]
            }
        });
    };
</script>

aa_contacts/templates/aa_contacts/corporation_contacts.html
{% extends 'aa_contacts/base.html' %}
{% load i18n %}

{% block page_title %}{% translate "Corporation Contacts" %}{% endblock page_title %}

{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock %}

{% block aacontactscontent %}
    {% include "framework/header/page-header.html" with title=corporation.corporation_name|add:" Contacts" %}
    {% if perms.aa_contacts.manage_corporation_contacts %}
        <div class="row justify-content-center my-3">
            <div class="col-6">
                <div class="card-group">
                    <div class="card text-center">
                        <div class="card-header">
                            {% translate "Last update" %}
                        </div>
                        <div class="card-body">
                            <p>{{ token.last_update|date:"d/m/Y G:i e" }}</p>
                        </div>
                    </div>
                    <div class="card text-center">
                        <div class="card-header">
                            {% translate "Actions" %}
                        </div>
                        <div class="card-body">
                            <a class="btn btn-primary" href="{% url "aa_contacts:update_corporation" corporation.pk %}">{% translate "Update" %}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {% include "aa_contacts/contact_list.html" with view_notes=perms.aa_contacts.view_corporation_notes edit_notes=perms.aa_contacts.manage_corporation_contacts contacts=contacts edit_url="aa_contacts:update_corporation_contact" %}
            </div>
        </div>
    </div>
{% endblock aacontactscontent %}

{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
    {% include "bundles/filterdropdown-js.html" %}
{% endblock extra_javascript %}

aa_contacts/templates/aa_contacts/edit_contact.html
{% extends "aa_contacts/base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block aacontactscontent %}
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title text-center"><img src="{{ contact.image_src }}" class="rounded me-2">{{ contact.contact_name }}</h5>
                <form method="post"> {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-primary">{% translate "Submit" %}</button>
                </form>
            </div>
        </div>
    </div>
{% endblock aacontactscontent %}

aa_contacts/templates/aa_contacts/index.html
{% extends 'aa_contacts/base.html' %}
{% load i18n %}

{% block aacontactscontent %}
    {% include "framework/header/page-header.html" with title="Contacts" %}
    <div class="col-12">
        <div class="card mb-3">
            <div class="card-header">
                <div class="card-title mb-0">{% translate "Alliances" %}</div>
            </div>

            <div class="card-body">
                <div class="row row-cols-md-2 row-cols-lg-4 row-cols-xl-6 justify-content-evenly">
                    {% for alliance in alliance_tokens %}
                        <div class="col">
                            <div class="card h-100 text-center">
                                <img src="{{ alliance.alliance.logo_url_256 }}" class="card-img-top" alt="{{ alliance.alliance.alliance_name }}">
                                <div class="card-body">
                                    <h5 class="card-title mb-3">{{ alliance.alliance.alliance_name }}</h5>
                                    <a href="{% url "aa_contacts:alliance_contacts" alliance.alliance_id %}" class="btn btn-primary">{% translate "View" %}</a>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <div class="col-12 text-center">
                            <h5>{% translate "No alliances available" %}</h5>
                        </div>
                    {% endfor %}
                    {% if perms.aa_contacts.manage_alliance_contacts %}
                        <div class="col">
                            <div class="card h-100">
                                <div class="card-body">
                                    <div class="d-flex justify-content-center align-items-center h-100">
                                        <a href="{% url "aa_contacts:add_alliance_token" %}" class="btn btn-primary">
                                            <i class="fa-solid fa-plus"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title mb-0">{% translate "Corporations" %}</div>
            </div>

            <div class="card-body">
                <div class="row row-cols-md-2 row-cols-lg-4 row-cols-xl-6 justify-content-evenly">
                    {% for corporation in corporation_tokens %}
                        <div class="col">
                            <div class="card h-100 text-center">
                                <img src="{{ corporation.corporation.logo_url_256 }}" class="card-img-top" alt="{{ corporation.corporation.corporation_name }}">
                                <div class="card-body">
                                    <h5 class="card-title mb-3">{{ corporation.corporation.corporation_name }}</h5>
                                    <a href="{% url "aa_contacts:corporation_contacts" corporation.corporation_id %}" class="btn btn-primary">{% translate "View" %}</a>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <div class="col-12 text-center">
                            <h5>{% translate "No corporations available" %}</h5>
                        </div>
                    {% endfor %}
                    {% if perms.aa_contacts.manage_corporation_contacts %}
                        <div class="col">
                            <div class="card h-100">
                                <div class="card-body">
                                    <div class="d-flex justify-content-center align-items-center h-100">
                                        <a href="{% url "aa_contacts:add_corporation_token" %}" class="btn btn-primary">
                                            <i class="fa-solid fa-plus"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock aacontactscontent %}

aa_contacts/templates/aa_contacts/react_base.html
{% extends 'aa_contacts/base.html' %}
{% load i18n %}

{% block extra_javascript %}
<script type="text/javascript">
    var BASE_URL = "/static/aa_contacts/react/";

    function loadCss(cssFiles) {
        (cssFiles || []).forEach(function (css) {
            console.log("Loading: ", css)

            $('<link>')
                .appendTo('head')
                .attr({
                    type: 'text/css',
                    rel: 'stylesheet',
                    href: css,
                });
        });
    }

    function loadScript(scriptUrl) {
        console.log("Loading JS: ", scriptUrl);
        var tag = document.createElement("script");
        tag.src = scriptUrl;
        tag.type = "module"; // you can set "module" if it's ESModules
        document.getElementsByTagName("head")[0].appendChild(tag);
    }

    function showLoaderError() {
        console.log("Unable to load react app, manifest file not accessible or corrupted");
        const error_div = document.querySelector("#error-div");
        const loading_div = document.querySelector("#loading-div");
        error_div.classList.toggle("d-none");
        loading_div.classList.toggle("d-none");
    }


    $.ajax(BASE_URL + 'manifest.json?version={{ version }}', {
        dataType: "json",
        success : function (manifest) {
            if (!manifest) {
                return showLoaderError();
            }

            // Option A) If we detect the “new format”:
            if (manifest["index.html"]) {
                // => handle the "example" manifest style
                const indexEntry = manifest["index.html"];
                const imports = (indexEntry.imports || []).map(f => BASE_URL + manifest[f].file);
                const cssFiles = (indexEntry.css || []).map(f => "/" + f);
                const mainJs = BASE_URL + indexEntry.file;

                loadCss(cssFiles);
                imports.forEach(loadScript);
                loadScript(mainJs);

            } else if (manifest.files && manifest.entrypoints) {
                let cssFiles = [];
                let jsFiles = [];

                manifest.entrypoints.forEach((entry) => {
                    if (entry.endsWith(".css")) {
                        cssFiles.push(BASE_URL + entry);
                    } else if (entry.endsWith(".js")) {
                        jsFiles.push(BASE_URL + entry);
                    }
                });
                loadCss(cssFiles);
                jsFiles.forEach(loadScript);
            } else {
                showLoaderError();
            }
        },
        error: showLoaderError,
        cache: false
    });
</script>
{% endblock extra_javascript %}

{% get_current_language as LANGUAGE_CODE %}
{% block content %}
<div id="root" lang="{{ LANGUAGE_CODE }}">
    <div id="app">
        <div id="loading-div" class="flex-container-main">
            <div class="text-center">
                <div>
                    <div class="lds-dual-ring-main"></div>
                </div>
                <h3>Loading Page</h3>
                <p>Please Wait</p>
            </div>
        </div>
        <div id="error-div" class="flex-container-main d-none">
            <div class="text-center">
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg"
                        width="100"
                        height="100"
                        fill="currentColor"
                        class="bi bi-exclamation-triangle error-anim-main"
                        viewBox="0 0 16 16">
                        <path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.146.146 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.163.163 0 0 1-.054.06.116.116 0 0 1-.066.017H1.146a.115.115 0 0 1-.066-.017.163.163 0 0 1-.054-.06.176.176 0 0 1 .002-.183L7.884 2.073a.147.147 0 0 1 .054-.057zm1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566z" />
                        <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995z" />
                    </svg>
                </div>
                <h3>Error Loading JavaScript</h3>
                <p>Check Browser Console for Logs</p>
                <p></p> {% comment %}???{% endcomment %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

aa_contacts/templates/aa_contacts/switch_frontend_version.html
{% load i18n %}

<li class="nav-item">
    {% if request.path|slice:":11" == "/contacts/r" %}
        <a class="nav-link" href="{% url "aa_contacts:dashboard" %}">{% translate "Legacy UI" %}</a>
    {% else %}
        <a class="nav-link" href="{% url "aa_contacts:react_view" %}">{% translate "New UI" %}</a>
    {% endif %}
</li>